# Generated by Django 4.1 on 2022-08-06 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the country", max_length=255
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "iso2",
                    models.CharField(
                        help_text="The ISO alpha-2 code of the country", max_length=2
                    ),
                ),
                (
                    "iso3",
                    models.CharField(
                        help_text="The ISO alpha-3 code of the country", max_length=3
                    ),
                ),
                (
                    "phone_code",
                    models.IntegerField(help_text="The phone code of the country"),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "geography_country",
                "ordering": ["name"],
            },
        ),
    ]
