# Generated by Django 4.1 on 2022-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="iso3",
            field=models.CharField(
                help_text="The ISO alpha-3 code of the country", max_length=3
            ),
        ),
    ]
