# Generated by Django 4.1 on 2022-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="archived",
            field=models.BooleanField(
                default=False, help_text="Is the country archived?"
            ),
        ),
    ]
