# Generated by Django 4.1rc1 on 2022-07-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
    ]
