# Generated by Django 4.1 on 2022-08-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_alter_country_archived"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="geography.country",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="phone_one_time_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="phone_verified_on",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
