# Generated by Django 4.1 on 2022-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_account_phone_one_time_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                help_text="The email of the user", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Is the email verified?"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email_verified_on",
            field=models.DateTimeField(
                editable=False,
                help_text="The date and time when the email was verified",
                null=True,
            ),
        ),
    ]
